version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk8
    commands:
      - echo "Installing dependencies..."
 

  pre_build:
    commands:
      - echo "Pre-build phase started on $(date)"


  build:
    commands:
      - echo "Build started on $(date)"
      - mvn  install

  post_build:
    commands:
      - echo "Build completed on $(date)"


artifacts:
  files:
    - 'target/profitmarket.war'
